language: node_js
node_js:
  "8"

notifications:
  email: false
  slack:
    rooms:
      - effektteam:E4fggEJ9TPpFLTpgn4eNEnGy#prosjekt_automagi
    on_success: never

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: production
